### PR TITLE
ccpp class parameter documentation update

### PR DESCRIPTION
**Pull request by jewelnuruddin**
according the issue number https://github.com/cristifalcas/puppet-abrt/issues/3 , fix ccpp classl parameter documentation

### CODE REVIEW

**Review by cristifalcas — APPROVED** [review]

**Comment by jewelnuruddin** [comment]
@cristifalcas,  thanks for approval

**Comment by cristifalcas** [comment]
Hi @jewelnuruddin . I don't work with puppet anymore, so, if you want to maintain this module, let me know. I will add a note in the readme and a link to our repo.

**Comment by jewelnuruddin** [comment]
Hello @cristifalcas , sure, I will be happy to maintain this module.

**Comment by cristifalcas** [comment]
Let me know your repo for this. I'll archive my repo and put a link to yours

**Comment by jewelnuruddin** [comment]
@cristifalcas, here is my repo https://github.com/jewelnuruddin/puppet-abrt

**Pull request closed without merging**
